language: python
python:
  - 3.8
install:
  - pip install codecov
script:
  python -m pytest --cov-config=.coveragerc_cpu --cov=fimpy tests/
  #coverage run tests.py
after_success:
  codecov -t 92805a53-76ae-4d04-a9a2-108142ee94d7
